name = "bing-submit-worker"
main = "index.ts"
compatibility_date = "2024-04-05"

[build]
command = "pnpm exec tsc"

[build.upload]
format = "modules"

[vars]
SITE_URL = "https://www.acmsz.top"

# Bing API Key 需要单独通过 secret 设置：
# wrangler secret put BING_API_KEY